name: Artifact generation
on: push
jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install nbconvert ipykernel pint matplotlib scipy open-atmos-jupyter-utils
      - run: sudo apt-get update
      - run: sudo apt-get install inkscape texlive-xetex texlive-fonts-recommended texlive-plain-generic pandoc
        #- uses: tecolicom/actions-use-apt-tools@v1
        #with:
          #tools: pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic
      - run: jupyter nbconvert --to pdf --execute lab*/lab*.ipynb
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: lab*/lab*.pdf
