name: lab01
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install nbconvert
      #- run: sudo apt-get install pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic inkscape
      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic inkscape
      - run: jupyter nbconvert --to pdf **.ipynb
      - uses: actions/upload-artifact@v4
        with:
          name: lab1
          path: lab1.pdf
